name: Android CI
on:
  push:
    branches:
      - master
      - develop
      - 'release**'
  pull_request:
    branches:
      - master
      - develop
      - 'release**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 26 ]
        target: [ default ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.29.0
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck

      - name: Create android test report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
